### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [fosskers/kanji#6]
```
kanji                          > /tmp/stack-e1324a2bddc8c287/kanji-3.4.1/lib/Data/Kanji/Types.hs:68:29: error:
kanji                          >     • Couldn't match type ‘T.Text’ with ‘Key’
kanji                          >       Expected: Level -> Key
kanji                          >         Actual: Level -> T.Text
kanji                          >     • In the first argument of ‘ToJSONKeyText’, namely ‘f’
kanji                          >       In the expression: ToJSONKeyText f g
kanji                          >       In an equation for ‘toJSONKey’:
kanji                          >           toJSONKey
kanji                          >             = ToJSONKeyText f g
kanji                          >             where
kanji                          >                 f = T.pack . show
kanji                          >                 g = text . T.pack . show
kanji                          >    |
kanji                          > 68 |   toJSONKey = ToJSONKeyText f g
kanji                          >    |                             ^
kanji                          > 
kanji                          > /tmp/stack-e1324a2bddc8c287/kanji-3.4.1/lib/Data/Kanji/Types.hs:105:29: error:
kanji                          >     • Couldn't match type ‘T.Text’ with ‘Key’
kanji                          >       Expected: CharCat -> Key
kanji                          >         Actual: CharCat -> T.Text
kanji                          >     • In the first argument of ‘ToJSONKeyText’, namely ‘f’
kanji                          >       In the expression: ToJSONKeyText f g
kanji                          >       In an equation for ‘toJSONKey’:
kanji                          >           toJSONKey
kanji                          >             = ToJSONKeyText f g
kanji                          >             where
kanji                          >                 f = T.pack . show
kanji                          >                 g = text . T.pack . show
kanji                          >     |
kanji                          > 105 |   toJSONKey = ToJSONKeyText f g
kanji                          >     |                             ^
```

**Comment by fosskers** [comment]
Ah thanks, perhaps I left too permissive of a bound.

**Comment by fosskers** [comment]
Fixed!

**Comment by juhp** [comment]
Thank you
